USE [master]
GO

CREATE DATABASE [ddev]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'ddev', FILENAME = N'C:\mssql\ddev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'ddev_log', FILENAME = N'C:\mssql\ddev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ddev] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ddev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ddev] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [ddev] SET ANSI_NULLS OFF
GO
ALTER DATABASE [ddev] SET ANSI_PADDING OFF
GO
ALTER DATABASE [ddev] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [ddev] SET ARITHABORT OFF
GO
ALTER DATABASE [ddev] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [ddev] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [ddev] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [ddev] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [ddev] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [ddev] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [ddev] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [ddev] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [ddev] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [ddev] SET  DISABLE_BROKER
GO
ALTER DATABASE [ddev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [ddev] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [ddev] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [ddev] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [ddev] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [ddev] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [ddev] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [ddev] SET RECOVERY FULL
GO
ALTER DATABASE [ddev] SET  MULTI_USER
GO
ALTER DATABASE [ddev] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [ddev] SET DB_CHAINING OFF
GO
ALTER DATABASE [ddev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [ddev] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [ddev] SET DELAYED_DURABILITY = DISABLED
GO
EXEC sys.sp_db_vardecimal_storage_format N'ddev', N'ON'
GO
ALTER DATABASE [ddev] SET QUERY_STORE = OFF
GO
USE [ddev]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [ddev]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Images](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Url] [nvarchar](4000) NOT NULL,
	[Description] [nvarchar](4000) NULL,
 CONSTRAINT [PK_Images] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Images] ON
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (1, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr05/15/9/anigif_enhanced-buzz-26388-1381844103-11.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (2, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr01/15/9/anigif_enhanced-buzz-31540-1381844535-8.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (3, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr05/15/9/anigif_enhanced-buzz-26390-1381844163-18.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (4, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr06/15/10/anigif_enhanced-buzz-1376-1381846217-0.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (5, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr03/15/9/anigif_enhanced-buzz-3391-1381844336-26.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (6, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr06/15/10/anigif_enhanced-buzz-29111-1381845968-0.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (7, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr03/15/9/anigif_enhanced-buzz-3409-1381844582-13.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (8, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr02/15/9/anigif_enhanced-buzz-19667-1381844937-10.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (9, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr05/15/9/anigif_enhanced-buzz-26358-1381845043-13.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (10, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr06/15/9/anigif_enhanced-buzz-18774-1381844645-6.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (11, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr06/15/9/anigif_enhanced-buzz-25158-1381844793-0.gif')
GO
INSERT [dbo].[Images] ([Id], [Url]) VALUES (12, N'http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr03/15/10/anigif_enhanced-buzz-11980-1381846269-1.gif')
GO
SET IDENTITY_INSERT [dbo].[Images] OFF
GO
